using System;
using System.Linq;
using System.Threading.Tasks;
using JetInteriorApp.Models;
using JetInteriorApp.Data;
using Microsoft.EntityFrameworkCore;
using Xunit;
// This script is used to test database integrity 
// Can data be written to/read from the database
// It does NOT test the JsonConfigurationRepository script
// - this is tackled by JsonConfigurationRepositoryTests.cs

public class DatabaseTester
{
    private readonly JetDbContext _db;

    public DatabaseTester(JetDbContext db)
    {
        _db = db;
    }

    public async Task RunTestsAsync()
    {
        Console.WriteLine("🔍 Testing database tables...\n");

        await TestTableAsync("Users", _db.Users.CountAsync());
        await TestTableAsync("JetConfigurations", _db.JetConfigurations.CountAsync());
        await TestTableAsync("InteriorComponents", _db.InteriorComponents.CountAsync());
        await TestTableAsync("ComponentSettings", _db.ComponentSettings.CountAsync());

        await CheckJetConfigurationUserLinksAsync();

        await CreateUserTestAsync();

        await Can_Add_JetConfiguration_For_User();

        await TestTableAsync("Users", _db.Users.CountAsync());
        await TestTableAsync("JetConfigurations", _db.JetConfigurations.CountAsync());
        await TestTableAsync("InteriorComponents", _db.InteriorComponents.CountAsync());
        await TestTableAsync("ComponentSettings", _db.ComponentSettings.CountAsync());

        Console.WriteLine("\nAll table checks complete.");
    }

    private async Task TestTableAsync(string tableName, Task<int> countTask)
    {
        try
        {
            int count = await countTask;
            Console.WriteLine($"PASS: {tableName}: {count} row(s)");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"ERROR: {tableName}: Error - {ex.Message}");
        }
    }

    private async Task CheckJetConfigurationUserLinksAsync()
    {
        Console.WriteLine("\nChecking JetConfigurations → Users foreign key integrity...");

        var validUserIds = await _db.Users.Select(u => u.UserID).ToListAsync();
        var configs = await _db.JetConfigurations.ToListAsync();

        foreach (var config in configs)
        {
            if (!validUserIds.Contains(config.UserID))
            {
                Console.WriteLine($" JetConfiguration '{config.Name}' has invalid UserID: {config.UserID}");
            }
        }

        Console.WriteLine("JetConfiguration user link check complete.");
    }

    public async Task CreateUserTestAsync()
    {
        try
        {
            // Create a new user using the factory method
            var newUser = User.CreateNew(
                username: "testuser_" + Guid.NewGuid(),
                email: "testuser@example.com",
                plainPassword: "SecurePassword123!"
            );

            // Map to persistence model (UserDB) for EF
            var newUserDB = new UserDB
            {
                UserID = newUser.UserID,
                Username = newUser.Username,
                Email = newUser.Email,
                PasswordHash = newUser.PasswordHash,
                CreatedAt = newUser.CreatedAt
            };

            _db.Users.Add(newUserDB);
            await _db.SaveChangesAsync();

            Console.WriteLine($"User created successfully with ID: {newUser.UserID}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error creating user: {ex.Message}");
        }
    }

    public async Task Can_Add_JetConfiguration_For_User()
    {
        // Get an existing user or create a new one if none exist
        var existingUser = await _db.Users.FirstOrDefaultAsync();

        if (existingUser == null)
        {
            var newUser = User.CreateNew(
                username: "autogenerated_" + Guid.NewGuid(),
                email: "autogen@example.com",
                plainPassword: "Password123!"
            );

            existingUser = new UserDB
            {
                UserID = newUser.UserID,
                Username = newUser.Username,
                Email = newUser.Email,
                PasswordHash = newUser.PasswordHash,
                CreatedAt = newUser.CreatedAt
            };

            _db.Users.Add(existingUser);
            await _db.SaveChangesAsync();

            Console.WriteLine($"Created fallback user: {existingUser.Username}");
        }
        else
        {
            Console.WriteLine($"Using existing user: {existingUser.UserID}, {existingUser.Username}");
        }

        // Create a JetConfiguration linked to the user
        var config = new JetConfiguration
        {
            ConfigID = Guid.NewGuid(),
            UserID = existingUser.UserID,
            Name = "Business Jet A",
            CabinDimensions = "10x3x2.5m",
            SeatingCapacity = 8,
            Version = 1,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        // Map to persistence model
        var configDB = new JetConfigurationDB
        {
            ConfigID = config.ConfigID,
            UserID = config.UserID,
            Name = config.Name,
            CabinDimensions = config.CabinDimensions,
            SeatingCapacity = config.SeatingCapacity,
            Version = config.Version ?? 0,
            CreatedAt = config.CreatedAt,
            UpdatedAt = config.UpdatedAt
        };

        _db.JetConfigurations.Add(configDB);
        await _db.SaveChangesAsync();

        // Verify it was added
        var retrieved = await _db.JetConfigurations
            .Include(c => c.User)
            .FirstOrDefaultAsync(c => c.Name == "Business Jet A");

        Assert.NotNull(retrieved);
        Assert.Equal(existingUser.UserID, retrieved.UserID);

        Console.WriteLine("✅ JetConfiguration successfully created and verified!");
    }
}
