// <auto-generated />
using System;
using JetInteriorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JetInteriorDesign.Migrations
{
    [DbContext(typeof(JetDbContext))]
    partial class JetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("JetInteriorApp.Data.ComponentSettings", b =>
                {
                    b.Property<Guid>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ComponentId");

                    b.ToTable("ComponentSettings");
                });

            modelBuilder.Entity("JetInteriorApp.Data.InteriorComponentDB", b =>
                {
                    b.Property<Guid>("ComponentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigID")
                        .HasColumnType("TEXT");

                    b.Property<float>("Cost")
                        .HasColumnType("REAL");

                    b.Property<float>("Depth")
                        .HasColumnType("REAL");

                    b.Property<float>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("ComponentID");

                    b.HasIndex("ConfigID");

                    b.ToTable("InteriorComponents");
                });

            modelBuilder.Entity("JetInteriorApp.Data.JetConfigurationDB", b =>
                {
                    b.Property<Guid>("ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigID");

                    b.HasIndex("UserID");

                    b.ToTable("JetConfigurations");
                });

            modelBuilder.Entity("JetInteriorApp.Data.UserDB", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JetInteriorApp.Data.ComponentSettings", b =>
                {
                    b.HasOne("JetInteriorApp.Data.InteriorComponentDB", null)
                        .WithOne("InteriorComponentSettings")
                        .HasForeignKey("JetInteriorApp.Data.ComponentSettings", "ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JetInteriorApp.Data.InteriorComponentDB", b =>
                {
                    b.HasOne("JetInteriorApp.Data.JetConfigurationDB", null)
                        .WithMany("InteriorComponents")
                        .HasForeignKey("ConfigID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JetInteriorApp.Data.JetConfigurationDB", b =>
                {
                    b.HasOne("JetInteriorApp.Data.UserDB", "User")
                        .WithMany("Configurations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JetInteriorApp.Data.InteriorComponentDB", b =>
                {
                    b.Navigation("InteriorComponentSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("JetInteriorApp.Data.JetConfigurationDB", b =>
                {
                    b.Navigation("InteriorComponents");
                });

            modelBuilder.Entity("JetInteriorApp.Data.UserDB", b =>
                {
                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
