using System;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using JIDS.Models; 
using JIDS.Data;
using Microsoft.EntityFrameworkCore;
using Xunit;

// This script is used to test database integrity 
// Can data be written to/read from the database
// It does NOT test the JsonConfigurationRepository script
// - this is tackled by JsonConfigurationRepositoryTests.cs

public class DatabaseTester
{
    private readonly JetDbContext _db;

    public DatabaseTester(JetDbContext db)
    {
        _db = db;
    }

    public async Task RunTestsAsync()
    {
        Console.WriteLine("🔍 Testing database tables...\n");

        // Test the four tables
        await TestTableAsync("Users", _db.Users.CountAsync());
        await TestTableAsync("JetConfigurations", _db.JetConfigurations.CountAsync());
        await TestTableAsync("InteriorComponents", _db.InteriorComponents.CountAsync());
        await TestTableAsync("ComponentSettings", _db.ComponentSettings.CountAsync());

        // Verify foreign key relationships
        await CheckJetConfigurationUserLinksAsync();

        //Create a test user & add to database
        await CreateUserTestAsync();

        // Create a test JetConfiguration & try add to a user  
        await Can_Add_JetConfiguration_For_User();

        // Test all tables again to check entry of new records
        await TestTableAsync("Users", _db.Users.CountAsync());
        await TestTableAsync("JetConfigurations", _db.JetConfigurations.CountAsync());
        await TestTableAsync("InteriorComponents", _db.InteriorComponents.CountAsync());
        await TestTableAsync("ComponentSettings", _db.ComponentSettings.CountAsync());

        Console.WriteLine("\n All table checks complete.");
    }

    private async Task TestTableAsync(string tableName, Task<int> countTask)
    {
        try
        {
            int count = await countTask;
            Console.WriteLine($"PASS: {tableName}: {count} row(s)");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"ERROR: {tableName}: Error - {ex.Message}");
        }
    }

    private async Task CheckJetConfigurationUserLinksAsync()
    {
        Console.WriteLine("\n Checking JetConfigurations → Users foreign key integrity...");

        var validUserIds = await _db.Users.Select(u => u.UserID).ToListAsync();
        var configs = await _db.JetConfigurations.ToListAsync();

        foreach (var config in configs)
        {
            if (!validUserIds.Contains(config.UserID))
            {
                Console.WriteLine($" JetConfiguration '{config.Name}' has invalid UserID: {config.UserID}");
            }
        }

        Console.WriteLine(" JetConfiguration user link check complete.");
    }

    public async Task CreateUserTestAsync()
    {
        try
        {
            // Create a new user
            var newUser = new User
            {
                Username = "testuser_" + Guid.NewGuid(), // unique name
                Email = "testuser@example.com",
                CreatedAt = DateTime.UtcNow
                // add other required fields here
            };

            //Set Password securely
            newUser.SetPassword("SecurePassword123!");

            //Convert to UserDB format so can be added to database
            var newUserDB = new UserDB
            {
                UserID = Guid.NewGuid(),              // generate a new ID for the database
                Username = newUser.Username,
                Email = newUser.Email,
                PasswordHash = newUser.PasswordHash,  // hashed password
                CreatedAt = newUser.CreatedAt
            };

            // Add user to the DbContext
            _db.Users.Add(newUserDB);

            // Commit to the database
            await _db.SaveChangesAsync();

            Console.WriteLine($"✅ User created successfully with ID: {newUser.UserID}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"❌ Error creating user: {ex.Message}");
        }
    }

    public async Task Can_Add_JetConfiguration_For_User()
    {
        // Try to get an existing user
        var existingUser = await _db.Users.FirstOrDefaultAsync();

        if (existingUser == null)
        {
            // If none exist, create one so test can proceed
            existingUser = new UserDB
            {
                UserID = Guid.NewGuid(),
                Username = "autogenerated_" + Guid.NewGuid(),
                Email = "autogen@example.com",
                CreatedAt = DateTime.UtcNow
            };
            _db.Users.Add(existingUser);
            await _db.SaveChangesAsync();

            Console.WriteLine($"Created fallback user: {existingUser.Username}");
        }
        else
        {
            Console.WriteLine($"Using existing user: {existingUser.UserID}, {existingUser.Username}");
        }

        // Create the in-memory model
        var config = new JetConfiguration
        {
            ConfigID = Guid.NewGuid(),
            UserID = existingUser.UserID,
            Name = "Business Jet A",
            CabinDimensions = "10x3x2.5m",
            SeatingCapacity = 8,
            Version = 1,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        // ✅ Convert to DB entity before saving
        var configDB = new JetConfigurationDB
        {
            ConfigID = config.ConfigID,
            UserID = config.UserID,
            Name = config.Name,
            CabinDimensions = config.CabinDimensions,
            SeatingCapacity = config.SeatingCapacity,
            Version = config.Version ?? 0,
            CreatedAt = config.CreatedAt,
            UpdatedAt = config.UpdatedAt,
        };

        // Add to database and save
        _db.JetConfigurations.Add(configDB);
        await _db.SaveChangesAsync();

        // Retrieve it back to validate
        var retrieved = await _db.JetConfigurations
            .Include(c => c.User)
            .FirstOrDefaultAsync(c => c.Name == "Business Jet A");

        Assert.NotNull(retrieved);
        Assert.Equal(existingUser.UserID, retrieved.UserID);

        Console.WriteLine("✅ JetConfiguration successfully created and verified!");
    }
}